name: Build and test XCode project

on: [push]

jobs:
  run_tests:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Select XCode version
      run: sudo xcode-select -switch /Applications/Xcode.app && /usr/bin/xcodebuild -version

    - name: Build and test
      run: xcodebuild test -scheme GitHubAction -project GitHubAction.xcodeproj -destination 'platform=macOS' | xcpretty && exit ${PIPESTATUS[0]}
